FROM ubuntu:14.04

RUN apt-get update && apt-get install -y \
    build-essential libtool autotools-dev autoconf pkg-config \
    libssl-dev libboost-all-dev libevent-dev bsdmainutils \
    libdb-dev libdb++-dev software-properties-common \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /bitcoin
COPY . .

RUN ./autogen.sh && \
    ./configure --without-gui --without-miniupnpc --with-incompatible-bdb --disable-tests && \
    make -j$(nproc)
